"""empty message

Revision ID: 54651726adc3
Revises: d9326bfe051d
Create Date: 2018-03-05 04:34:47.152692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54651726adc3'
down_revision = 'd9326bfe051d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'password')
    # ### end Alembic commands ###
